### ISSUE TITLE
School 검색

### ISSUE THREAD

**Issue by gimhanul** [gimhanul/Stupetition-server#10]
### ✨ Describe

사용자가 School 을 선택할 수 있도록 검색 기능을 만들어야 합니다.

### ✅ Tasks

- [x] School repository에 검색 기능 추가
- [x] School search service
- [x] School search controller
