### ISSUE TITLE
Board 생성

### ISSUE THREAD

**Issue by gimhanul** [gimhanul/Stupetition-server#14]
### ✨ Describe

User가 Board를 생성할 수 있어야 합니다.

### ✅ Tasks

- [x] Board Entity 작성
- [x] Board - Board agreer - User 다대다 친구
- [x] Board 생성 dto
- [x] Board 생성 service, controller
