### ISSUE TITLE
school에 인원 수 column 추가

### ISSUE THREAD

**Issue by gimhanul** [gimhanul/Stupetition-server#30]
### ✨ Describe

school에 인원 수 column 추가해야 합니다.

### ✅ Tasks

- [x] school에 인원 수 column 추가
- [x] user가 school 에 가입할 때 마다 인원수 +1
- [x] user가 탈퇴하거나, school 변경 시 인원 수 -1
